"""maintenance module

Revision ID: e94ebd5070d7
Revises: 93c8fe876d1c
Create Date: 2026-07-10 23:18:36.566780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94ebd5070d7'
down_revision = '93c8fe876d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('issue', sa.String(length=250), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('reported_date', sa.Date(), nullable=True),
    sa.Column('resolved_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance')
    # ### end Alembic commands ###
